# Generated by Django 2.0 on 2018-08-21 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forumcomment', to='forum.ForumPost'),
        ),
    ]
