# Generated by Django 2.0 on 2018-08-21 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20180821_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumcomment',
            name='post',
        ),
        migrations.AddField(
            model_name='forumcomment',
            name='forumpost',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='forumcomments', to='forum.ForumPost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
